import Head from "next/head";
import Image from "next/image";
import { Fragment } from "react";

// MUI
import { Stack } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
//

import { main_logo_address } from "@housing/constants";
import { SearchBox } from "@housing/lib";
//

export const getStaticProps = () => {
  return {
    props: {},
  };
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Housing Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Fragment>
        <CssBaseline />
        <Container maxWidth="md" sx={{ height: "100vh" }}>
          <Stack justifyContent="center" textAlign="center" mt={8}>
            {/* Logo */}
            <Box component="span">
              <Image
                src={main_logo_address}
                alt="Vercel Logo"
                width={400}
                height={400}
              />
            </Box>
            {/* Search Box */}
            <SearchBox />
          </Stack>
        </Container>
      </Fragment>
    </div>
  );
}
